### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by sk8nfool** [rianhunter/dbxfs#25]
Hi,
I am using dbxfs 1.0.40 on Ubuntu 18.04. I am getting incorrect data when accessing a particular file. If I mount my dropbox on dbx with dbxfs and run
`md5sum dbx/IMG_0784.MOV`
I get
`1284b0086df766683bc43abd52aa2c8d  dbx/IMG_0784.MOV`
but if I use the Dropbox.com web page and down load the same file to tmp/IMG_0784.MOV and run
`md5sum tmp/IMG_0784.MOV`
I get
`97edf3902a9d84f9d0b88faf242565e4  tmp/IMG_0784.MOV`
How do I find what's happening?
BTW the file in tmp/IMG_0784.MOV plays fine using VLC but the one in dbx doesn't

**Comment by rianhunter** [comment]
Yes, I've been noticing some download issues with Dropbox as well. Thank you for reporting, this is another valuable data point. I don't think this is due to dbxfs but I'm still investigating. What's the size of your movie file?

**Comment by sk8nfool** [comment]
272MB (285,151,527) - interesting. I tried comparing the two files to see
if there was something like a block of zeroes or the like. The first
mismatching byte is 196609. That turns out to be 0x30001! Curiouser and
curiouser says a cat!


On Dec 21, 2018 6:20 PM, "Rian Hunter" <notifications@github.com> wrote:

Yes, I've been noticing some download issues with Dropbox as well. Thank
you for reporting, this is another valuable data point. I don't think this
is due to dbxfs but I'm still investigating. What's the size of your movie
file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rianhunter/dbxfs/issues/25#issuecomment-449521865>, or mute
the thread

**Comment by sk8nfool** [comment]
No Problem. Your request is a bit open ended. To give your request a go I
hexdumped both files and did an sdiff on them. There were some interesting
diffs
bytes 0 - 0x2FFFF matched
bytes 0x30000 - 0x5FFFF differed
    00030000  03 c8 6a de 9a 2d 6e b4  36 9d 0b f7 55 9e 08 fa  | |
00030000  ec 78 5e dc a4 da 9a be  58 a2 b4 89 b7 70 c1 3c  |

bytes 0x60000 - 0x6FFFF matched
bytes 0x70000 - EOF differ
    00070000  b5 37 db 4d bd f3 a3 bb  ef 69 5e 13 91 67 6d 36  | |
00070000  bb 63 22 b6 80 42 ce 9c  74 b5 9f f8 0a bc 6f ab  |

keep in mind these are MOV files so this block comparison won't find
shifted blocks too well.
Also not that I have this identical file in a different dropbox. That one
works fine although the files are in different folders.

**Comment by varenc** [comment]
Hi @sk8nfool ! I'm jumping in sort of randomly on this, but file corruption errors are pretty fascinating to me!  If possible, could you try re-downloading the same file over the Dropbox API but with a different app?

You could try using `rclone` though that will require some setup.  Alternatively just use the Dropbox API explorer here: https://dropbox.github.io/dropbox-api-v2-explorer/#files_download

In-browser file downloading won't work, but you can copy the `curl` command it generates for you and just add `-o some_file` to download it. From there you can see which of the md5s the download file matches.

**Comment by sk8nfool** [comment]
I'll try that in the morning. But another data point - I installed dbxfs on
another computer and it works fine. The first machine is an ASUS laptop and
this new setup is on a Dell mini tower. I think they're both 64 bit
machines. One difference is the laptop is running two instances with
different accounts. This problem only showed up when I added the second
account.

**Comment by sk8nfool** [comment]
well - once I figured out where to find "the curl command it generates"
("it" turns out to be the API explorer) I tried that. It didn't work.

$ curl -X POST https://content.dropboxapi.com/2/files/download \
>   --header 'Authorization: Bearer <...>' \
>   --header 'Dropbox-API-Arg: {"path":"IMG_0784.mov"}' -o x

Error in call to API function "files/download": HTTP header
"Dropbox-API-Arg": path: 'IMG_0784.mov' did not match pattern
'(/(.|[\r\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'

I'm going to have to read some documentation to find where the pattern
comes from.

**Comment by sk8nfool** [comment]
Got it - path must be rooted with "/" (at least). Once I set the path to
"/IMG_0784.MOV" the curl command worked AND the md5sum was correct. Does
this mean the problem is with dbxfs?

**Comment by rianhunter** [comment]
By any chance, was the corrupted file a shared file between these two accounts?Did you ever run two instances of dbxfs on the same account?

**Comment by sk8nfool** [comment]
@rianhunter Yes - the file in question was received from another person - I believe it was shared using Dropbox via email. I don't remember the details of the process except I received an email saying that she (the other person) shared a file with me. i don't remember how I added it to my DB. I don't believe I still have the emails but I'll check and get back to you.

**Comment by sk8nfool** [comment]
wow - still have the email! It was from a noreply address with a reply-to aimed at the original sender. It had a button to view the file (it is a .mov file so it opened a player page). There is a download that allows me to save the file to my DB - my guess is that I chose that. Not sure.
FYI - there are 3 accounts involved here. The original account and my two accounts. The owner of the original file share it with me using my public email address but my main dropbox account (not the one causing this issue) is associated with a different email address. I kind of recall tripping over this but don't remember what happened and how I resolved it. The bottom line is what's going wrong and who's at fault.

To get away from the above confusion I'm going to upload a good copy of the file to my db using a different name and then try to access the new file via dbxfs and see what happens.

**Comment by sk8nfool** [comment]
Well - don't know what to say - the problem seems to have gone away. I was forced to reconnect because of an error about transport endpoint not being connected (or something). I was also told that there's a new version (1.0.41 vs 1.0.40). I haven't upgraded yet.

**Comment by sk8nfool** [comment]
I do know what to say - ID 10 T error! I was on the wrong machine. The error occurs on my laptop not my tower. So to answer your question - yes - I have two instances of dbxfs mounted on my desktop now (just set it up) and everything works. BTW - there are actually 3 dbxfs mounts on my minitower and they all work.

**Comment by rianhunter** [comment]
Do you have multiple instances connected to the same account?

**Comment by sk8nfool** [comment]
yes - the one having trouble is braun-asus an ASUS laptop
The one that works is a Dell mini-tower.

I just tried verifying the installation by running md5sum on the various
files

/usr/bin/python3.6

$HOME/.local/bin/dbxfs

$HOME/.local/lib/python3.6/site-packages/dbxfs/*

and they all were the same except the laptop didn't have
$HOME/.local/lib/python3.6/site-packages/dbxfs/wrap_errors.py

**Comment by rianhunter** [comment]
Sorry, just want to be 100% clear: your braun Asus laptop runs multiple instances of dbxfs connected to the same account?

**Comment by sk8nfool** [comment]
Sorry for the delay - too much going on.
I just verified that having 2 mounts for the same DB account and the same
Ubuntu account produce the same result: two  So to summarize(?)
Ubuntu laptop
single account
2 dbxfs mount points
2 dbxfs config files (implying 2 DB authorization strings)
Dropbox
Single account
2 identical files
in each dbxfs mount2 the 2 files have different md5sums but in the Dropbox
sync'd folder the 2 files have identical md5sums. FYI, IIRC the second of
the 2 files was created by downloading the original using the DB web page,
verifying the md5sum, renaming the downloaded copy and moving that to my
local DB. I just downloaded both files from my DB to a temp folder and
check their me5sums - both are the same (and both play).

**Comment by rianhunter** [comment]
No worries, it's been a hectic time.I have confirmed a download issue with Dropbox and I'm working with them on another private thread. After investigating that issue more, it doesn't seem related to this issue.I believe this issue was due to running multiple versions of dbxfs at the same time. This will be fixed in a pending release. Thanks for helping nail this down!

**Comment by sk8nfool** [comment]
".. running multiple versions .." - do you mean "versions" or "instances"?
i ask because i was only running a single instance of a single version when
I ran into this problem.

**Comment by rianhunter** [comment]
Oh? I thought you said you had two dbxfs mount points on the same machine. Was that not case? You were running only a single dbxfs mount point when you ran into this issue originally?

**Comment by sk8nfool** [comment]
hmm - I believe that is correct but I've been fooling with this so much
that I may be miss-remembering. That's kind of why I asked how to start
from scratch. So far I'm assuming using a different config file effectively
causes dbxfs to start over (at least I'm asked to reconnect to tthe dropbox
server). However I don't know how to restart any cache you might be using.

**Comment by rianhunter** [comment]
This should be fixed in 1dde10c6361a3026a086d8672694dbcc7d86b535, if not please report again!

**Comment by sk8nfool** [comment]
It does but don't forget to flush the cache otherwise the problem may appear to still exist.
